// Types
import { Product } from "@/lib/models/Product";

const products: Product[] = [
	{
		id: 1,
		name: "Rectangular Prescription",
		slug: "rectangular-prescription",
		image: "/images/products/nike-air-max-270.jpg",
		banner: "/images/products/nike-air-max-270-banner.jpg",
		price: 52.0,
		previousPrice: 100.0,
		brand: "Rectangular",
		description:
			"Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		category: ["rectangular", "top", "prescription"],
		rating: 4.5,
		countInStock: 5,
		variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		features: ["Lightweight", "Comfortable", "Durable"],
		tags: ["rectangular", "prescription"],
		createdAt: "2022-01-01",
	},
	{
		id: 2,
		name: "Double Round Sunglasses",
		slug: "double-round-sunglasses",
		image: "/images/products/round-prescription-Eyewear-Frames.jpg",
		banner: "/images/products/round-prescription-Eyewear-Frames.jpg",
		price: 325,
		previousPrice: 300,
		brand: "Round",
		description:
			"Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		category: ["round", "top", "sunglasses"],
		rating: 4.9,
		countInStock: 5,
		variants: ["black", "white"],
		reviews: ["Great product", "Nice shoes"],
		features: ["Lightweight", "Comfortable", "Durable"],
		tags: ["round", "sunglasses"],
		createdAt: "2022-01-01",
	},
	{
		id: 3,
		name: "Aviator Sunglasses",
		slug: "aviator-sunglasses",
		image: "/images/products/round-prescription-Eyewear-Frames.jpg",
		banner: "/images/products/round-prescription-Eyewear-Frames.jpg",
		price: 160,
		brand: "Aviator",
		description:
			"Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		category: ["aviator", "top", "sunglasses"],
		rating: 4.9,
		countInStock: 5,
		variants: ["black", "white"],
		reviews: ["Great product", "Nice shoes"],
		features: ["Lightweight", "Comfortable", "Durable"],
		tags: ["nike", "air max", "270"],
		createdAt: "2022-01-01",
	},
	{
		id: 4,
		name: "Cat Eye Sunglasses",
		slug: "cat-eye-sunglasses",
		image: "/images/products/round-prescription-Eyewear-Frames.jpg",
		banner: "/images/products/round-prescription-Eyewear-Frames.jpg",
		price: 96,
		previousPrice: 90,
		brand: "Cat Eye",
		description:
			"Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		category: ["top", "sunglasses", "cat-eye"],
		rating: 4.9,
		countInStock: 5,
		variants: ["black", "white"],
		reviews: ["Great product", "Nice shoes"],
		features: ["Lightweight", "Comfortable", "Durable"],
		tags: ["nike", "air max", "270"],
		createdAt: "2022-01-01",
	},
	{
		id: 5,
		name: "Gradient Aviator Sunglasses",
		slug: "gradient-aviator-sunglasses",
		image: "/images/products/nike-air-max-270.jpg",
		banner: "/images/products/nike-air-max-270-banner.jpg",
		price: 212,
		previousPrice: 200,
		brand: "Gradient",
		description:
			"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed auctor, purus sit amet volutpat.",
		category: ["aviator", "sunglasses", "top"],
		rating: 4.5,
		countInStock: 5,
		variants: ["black", "white"],
		reviews: ["Great product", "Nice shoes"],
		features: ["Lightweight", "Comfortable", "Durable"],
		tags: ["nike", "air max", "270"],
		createdAt: "2022-01-01",
	},
	{
		id: 6,
		name: "Square Prescription Eyeglass Frames",
		slug: "square-prescription-eyeglass-frames",
		image: "/images/products/round-prescription-Eyewear-Frames.jpg",
		banner: "/images/products/round-prescription-Eyewear-Frames.jpg",
		price: 100,
		previousPrice: 120,
		brand: "Square",
		description:
			"Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		category: ["square", "top", "prescription"],
		rating: 4.9,
		countInStock: 5,
		variants: ["black", "white"],
		reviews: ["Great product", "Nice shoes"],
		features: ["Lightweight", "Comfortable", "Durable"],
		tags: ["nike", "air max", "270"],
		createdAt: "2022-01-01",
	},
	{
		id: 7,
		name: "Round Flat Lens Sunglasses",
		slug: "round-flat-lens-sunglasses",
		image: "/images/products/round-prescription-Eyewear-Frames.jpg",
		banner: "/images/products/round-prescription-Eyewear-Frames.jpg",
		price: 368,
		previousPrice: 375,
		brand: "Round",
		description:
			"Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		category: ["round", "top", "sunglasses"],
		rating: 4.9,
		countInStock: 5,
		variants: ["black", "white"],
		reviews: ["Great product", "Nice shoes"],
		features: ["Lightweight", "Comfortable", "Durable"],
		tags: ["nike", "air max", "270"],
		createdAt: "2022-01-01",
	},
	{
		id: 8,
		name: "Clubmaster Square Prescription",
		slug: "clubmaster-square-prescription",
		image: "/images/products/round-prescription-Eyewear-Frames.jpg",
		banner: "/images/products/round-prescription-Eyewear-Frames.jpg",
		price: 212,
		brand: "Round",
		description:
			"Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		category: ["glasses", "top"],
		rating: 4.9,
		countInStock: 5,
		variants: ["black", "white"],
		reviews: ["Great product", "Nice shoes"],
		features: ["Lightweight", "Comfortable", "Durable"],
		tags: ["nike", "air max", "270"],
		createdAt: "2022-01-01",
	},
	{
		id: 9,
		name: "Round Prescription Eyewear Frames",
		slug: "round-prescription-eyewear-frames",
		image: "/images/products/nike-air-max-270.jpg",
		banner: "/images/products/nike-air-max-270-banner.jpg",
		price: 48,
		brand: "Round",
		description:
			"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed auctor, purus sit amet volutpat.",
		category: ["round", "top", "prescription"],
		rating: 4.5,
		countInStock: 5,
		variants: ["black", "white"],
		reviews: ["Great product", "Nice shoes"],
		features: ["Lightweight", "Comfortable", "Durable"],
		tags: ["nike", "air max", "270"],
		createdAt: "2022-01-01",
	},
	{
		id: 10,
		name: "Clubround Round Sunglasses",
		slug: "clubround-round-sunglasses",
		image: "/images/products/round-prescription-Eyewear-Frames.jpg",
		banner: "/images/products/round-prescription-Eyewear-Frames.jpg",
		price: 100,
		previousPrice: 120,
		brand: "Clubround",
		description:
			"Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		category: ["round", "top", "sunglasses"],
		rating: 4.9,
		countInStock: 5,
		variants: ["black", "white"],
		reviews: ["Great product", "Nice shoes"],
		features: ["Lightweight", "Comfortable", "Durable"],
		tags: ["nike", "air max", "270"],
		createdAt: "2022-01-01",
	},
	{
		id: 11,
		name: "Round Prescription Eyeglass Frames",
		slug: "round-prescription-eyeglass-frames",
		image: "/images/products/round-prescription-Eyewear-Frames.jpg",
		banner: "/images/products/round-prescription-Eyewear-Frames.jpg",
		price: 410,
		brand: "Round",
		description:
			"Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		category: ["round", "top", "prescription"],
		rating: 4.9,
		countInStock: 5,
		variants: ["black", "white"],
		reviews: ["Great product", "Nice shoes"],
		features: ["Lightweight", "Comfortable", "Durable"],
		tags: ["nike", "air max", "270"],
		createdAt: "2022-01-01",
	},
	{
		id: 12,
		name: "Clubmaster Square Sunglasses",
		slug: "clubmaster-square-sunglasses",
		image: "/images/products/round-prescription-Eyewear-Frames.jpg",
		banner: "/images/products/round-prescription-Eyewear-Frames.jpg",
		price: 430,
		brand: "Clubmaster",
		description:
			"Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		category: ["sunglasses", "top", "square"],
		rating: 4.9,
		countInStock: 5,
		variants: ["black", "white"],
		reviews: ["Great product", "Nice shoes"],
		features: ["Lightweight", "Comfortable", "Durable"],
		tags: ["nike", "air max", "270"],
		createdAt: "2022-01-01",
	},
];

export default products;
