const dummyProducts = [
	{
		id: 1,
		name: "Rectangular Prescription",
		slug: "rectangular-prescription",
		price: 52.0,
		previousPrice: 100.0,
		brand: "Rectangular",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [5, 1, 10],
		rating: 4.5,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["rectangular", "prescription"],
	},
	{
		id: 2,
		name: "Double Round Sunglasses",
		slug: "double-round-sunglasses",
		price: 325,
		previousPrice: 300,
		brand: "Round",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [6, 1, 7],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["round", "sunglasses"],
	},
	{
		id: 3,
		name: "Aviator Sunglasses",
		slug: "aviator-sunglasses",
		price: 160,
		brand: "Aviator",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [8, 1, 7],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 4,
		name: "Cat Eye Sunglasses",
		slug: "cat-eye-sunglasses",
		price: 96,
		previousPrice: 90,
		brand: "Cat Eye",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [1, 7, 9],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 5,
		name: "Gradient Aviator Sunglasses",
		slug: "gradient-aviator-sunglasses",
		price: 212,
		previousPrice: 200,
		brand: "Gradient",
		perex: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed auctor, purus sit amet volutpat.",
		categories: [8, 7, 1],
		rating: 4.5,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 6,
		name: "Square Prescription Eyeglass Frames",
		slug: "square-prescription-eyeglass-frames",
		price: 100,
		previousPrice: 120,
		brand: "Square",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [13, 1, 10],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 7,
		name: "Round Flat Lens Sunglasses",
		slug: "round-flat-lens-sunglasses",
		price: 368,
		previousPrice: 375,
		brand: "Round",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [6, 1, 7],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 8,
		name: "Clubmaster Square Prescription",
		slug: "clubmaster-square-prescription",
		price: 212,
		brand: "Round",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [10, 1],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 9,
		name: "Round Prescription Eyewear Frames",
		slug: "round-prescription-eyewear-frames",
		price: 48,
		brand: "Round",
		perex: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed auctor, purus sit amet volutpat.",
		categories: [6, 1, 10],
		rating: 4.5,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 10,
		name: "Clubround Round Sunglasses",
		slug: "clubround-round-sunglasses",
		price: 100,
		previousPrice: 120,
		brand: "Clubround",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [6, 1, 7],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 11,
		name: "Round Prescription Eyeglass Frames",
		slug: "round-prescription-eyeglass-frames",
		price: 410,
		brand: "Round",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [6, 1, 10],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 12,
		name: "Clubmaster Square Sunglasses",
		slug: "clubmaster-square-sunglasses",
		price: 430,
		brand: "Clubmaster",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [7, 1, 13],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 1,
		name: "Rectangular Prescription",
		slug: "rectangular-prescription",
		price: 52.0,
		previousPrice: 100.0,
		brand: "Rectangular",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [5, 1, 10],
		rating: 4.5,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["rectangular", "prescription"],
	},
	{
		id: 2,
		name: "Double Round Sunglasses",
		slug: "double-round-sunglasses",
		price: 325,
		previousPrice: 300,
		brand: "Round",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [6, 1, 7],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["round", "sunglasses"],
	},
	{
		id: 3,
		name: "Aviator Sunglasses",
		slug: "aviator-sunglasses",
		price: 160,
		brand: "Aviator",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [8, 1, 7],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 4,
		name: "Cat Eye Sunglasses",
		slug: "cat-eye-sunglasses",
		price: 96,
		previousPrice: 90,
		brand: "Cat Eye",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [1, 7, 9],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 5,
		name: "Gradient Aviator Sunglasses",
		slug: "gradient-aviator-sunglasses",
		price: 212,
		previousPrice: 200,
		brand: "Gradient",
		perex: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed auctor, purus sit amet volutpat.",
		categories: [8, 7, 1],
		rating: 4.5,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 6,
		name: "Square Prescription Eyeglass Frames",
		slug: "square-prescription-eyeglass-frames",
		price: 100,
		previousPrice: 120,
		brand: "Square",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [13, 1, 10],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 7,
		name: "Round Flat Lens Sunglasses",
		slug: "round-flat-lens-sunglasses",
		price: 368,
		previousPrice: 375,
		brand: "Round",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [6, 1, 7],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 8,
		name: "Clubmaster Square Prescription",
		slug: "clubmaster-square-prescription",
		price: 212,
		brand: "Round",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [10, 1],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 9,
		name: "Round Prescription Eyewear Frames",
		slug: "round-prescription-eyewear-frames",
		price: 48,
		brand: "Round",
		perex: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed auctor, purus sit amet volutpat.",
		categories: [6, 1, 10],
		rating: 4.5,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 10,
		name: "Clubround Round Sunglasses",
		slug: "clubround-round-sunglasses",
		price: 100,
		previousPrice: 120,
		brand: "Clubround",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [6, 1, 7],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 11,
		name: "Round Prescription Eyeglass Frames",
		slug: "round-prescription-eyeglass-frames",
		price: 410,
		brand: "Round",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [6, 1, 10],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 12,
		name: "Clubmaster Square Sunglasses",
		slug: "clubmaster-square-sunglasses",
		price: 430,
		brand: "Clubmaster",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [7, 1, 13],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},

	{
		id: 1,
		name: "Rectangular Prescription",
		slug: "rectangular-prescription",
		price: 52.0,
		previousPrice: 100.0,
		brand: "Rectangular",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [5, 1, 10],
		rating: 4.5,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["rectangular", "prescription"],
	},
	{
		id: 2,
		name: "Double Round Sunglasses",
		slug: "double-round-sunglasses",
		price: 325,
		previousPrice: 300,
		brand: "Round",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [6, 1, 7],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["round", "sunglasses"],
	},
	{
		id: 3,
		name: "Aviator Sunglasses",
		slug: "aviator-sunglasses",
		price: 160,
		brand: "Aviator",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [8, 1, 7],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 4,
		name: "Cat Eye Sunglasses",
		slug: "cat-eye-sunglasses",
		price: 96,
		previousPrice: 90,
		brand: "Cat Eye",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [1, 7, 9],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 5,
		name: "Gradient Aviator Sunglasses",
		slug: "gradient-aviator-sunglasses",
		price: 212,
		previousPrice: 200,
		brand: "Gradient",
		perex: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed auctor, purus sit amet volutpat.",
		categories: [8, 7, 1],
		rating: 4.5,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 6,
		name: "Square Prescription Eyeglass Frames",
		slug: "square-prescription-eyeglass-frames",
		price: 100,
		previousPrice: 120,
		brand: "Square",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [13, 1, 10],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 7,
		name: "Round Flat Lens Sunglasses",
		slug: "round-flat-lens-sunglasses",
		price: 368,
		previousPrice: 375,
		brand: "Round",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [6, 1, 7],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 8,
		name: "Clubmaster Square Prescription",
		slug: "clubmaster-square-prescription",
		price: 212,
		brand: "Round",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [10, 1],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 9,
		name: "Round Prescription Eyewear Frames",
		slug: "round-prescription-eyewear-frames",
		price: 48,
		brand: "Round",
		perex: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed auctor, purus sit amet volutpat.",
		categories: [6, 1, 10],
		rating: 4.5,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 10,
		name: "Clubround Round Sunglasses",
		slug: "clubround-round-sunglasses",
		price: 100,
		previousPrice: 120,
		brand: "Clubround",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [6, 1, 7],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 11,
		name: "Round Prescription Eyeglass Frames",
		slug: "round-prescription-eyeglass-frames",
		price: 410,
		brand: "Round",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [6, 1, 10],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 12,
		name: "Clubmaster Square Sunglasses",
		slug: "clubmaster-square-sunglasses",
		price: 430,
		brand: "Clubmaster",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [7, 1, 13],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},

	{
		id: 1,
		name: "Rectangular Prescription",
		slug: "rectangular-prescription",
		price: 52.0,
		previousPrice: 100.0,
		brand: "Rectangular",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [5, 1, 10],
		rating: 4.5,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["rectangular", "prescription"],
	},
	{
		id: 2,
		name: "Double Round Sunglasses",
		slug: "double-round-sunglasses",
		price: 325,
		previousPrice: 300,
		brand: "Round",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [6, 1, 7],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["round", "sunglasses"],
	},
	{
		id: 3,
		name: "Aviator Sunglasses",
		slug: "aviator-sunglasses",
		price: 160,
		brand: "Aviator",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [8, 1, 7],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 4,
		name: "Cat Eye Sunglasses",
		slug: "cat-eye-sunglasses",
		price: 96,
		previousPrice: 90,
		brand: "Cat Eye",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [1, 7, 9],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 5,
		name: "Gradient Aviator Sunglasses",
		slug: "gradient-aviator-sunglasses",
		price: 212,
		previousPrice: 200,
		brand: "Gradient",
		perex: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed auctor, purus sit amet volutpat.",
		categories: [8, 7, 1],
		rating: 4.5,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 6,
		name: "Square Prescription Eyeglass Frames",
		slug: "square-prescription-eyeglass-frames",
		price: 100,
		previousPrice: 120,
		brand: "Square",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [13, 1, 10],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 7,
		name: "Round Flat Lens Sunglasses",
		slug: "round-flat-lens-sunglasses",
		price: 368,
		previousPrice: 375,
		brand: "Round",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [6, 1, 7],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 8,
		name: "Clubmaster Square Prescription",
		slug: "clubmaster-square-prescription",
		price: 212,
		brand: "Round",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [10, 1],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 9,
		name: "Round Prescription Eyewear Frames",
		slug: "round-prescription-eyewear-frames",
		price: 48,
		brand: "Round",
		perex: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed auctor, purus sit amet volutpat.",
		categories: [6, 1, 10],
		rating: 4.5,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 10,
		name: "Clubround Round Sunglasses",
		slug: "clubround-round-sunglasses",
		price: 100,
		previousPrice: 120,
		brand: "Clubround",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [6, 1, 7],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 11,
		name: "Round Prescription Eyeglass Frames",
		slug: "round-prescription-eyeglass-frames",
		price: 410,
		brand: "Round",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [6, 1, 10],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 12,
		name: "Clubmaster Square Sunglasses",
		slug: "clubmaster-square-sunglasses",
		price: 430,
		brand: "Clubmaster",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [7, 1, 13],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},

	{
		id: 1,
		name: "Rectangular Prescription",
		slug: "rectangular-prescription",
		price: 52.0,
		previousPrice: 100.0,
		brand: "Rectangular",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [5, 1, 10],
		rating: 4.5,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["rectangular", "prescription"],
	},
	{
		id: 2,
		name: "Double Round Sunglasses",
		slug: "double-round-sunglasses",
		price: 325,
		previousPrice: 300,
		brand: "Round",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [6, 1, 7],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["round", "sunglasses"],
	},
	{
		id: 3,
		name: "Aviator Sunglasses",
		slug: "aviator-sunglasses",
		price: 160,
		brand: "Aviator",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [8, 1, 7],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 4,
		name: "Cat Eye Sunglasses",
		slug: "cat-eye-sunglasses",
		price: 96,
		previousPrice: 90,
		brand: "Cat Eye",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [1, 7, 9],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 5,
		name: "Gradient Aviator Sunglasses",
		slug: "gradient-aviator-sunglasses",
		price: 212,
		previousPrice: 200,
		brand: "Gradient",
		perex: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed auctor, purus sit amet volutpat.",
		categories: [8, 7, 1],
		rating: 4.5,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 6,
		name: "Square Prescription Eyeglass Frames",
		slug: "square-prescription-eyeglass-frames",
		price: 100,
		previousPrice: 120,
		brand: "Square",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [13, 1, 10],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 7,
		name: "Round Flat Lens Sunglasses",
		slug: "round-flat-lens-sunglasses",
		price: 368,
		previousPrice: 375,
		brand: "Round",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [6, 1, 7],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 8,
		name: "Clubmaster Square Prescription",
		slug: "clubmaster-square-prescription",
		price: 212,
		brand: "Round",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [10, 1],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 9,
		name: "Round Prescription Eyewear Frames",
		slug: "round-prescription-eyewear-frames",
		price: 48,
		brand: "Round",
		perex: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed auctor, purus sit amet volutpat.",
		categories: [6, 1, 10],
		rating: 4.5,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 10,
		name: "Clubround Round Sunglasses",
		slug: "clubround-round-sunglasses",
		price: 100,
		previousPrice: 120,
		brand: "Clubround",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [6, 1, 7],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 11,
		name: "Round Prescription Eyeglass Frames",
		slug: "round-prescription-eyeglass-frames",
		price: 410,
		brand: "Round",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [6, 1, 10],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 12,
		name: "Clubmaster Square Sunglasses",
		slug: "clubmaster-square-sunglasses",
		price: 430,
		brand: "Clubmaster",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [7, 1, 13],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},

	{
		id: 1,
		name: "Rectangular Prescription",
		slug: "rectangular-prescription",
		price: 52.0,
		previousPrice: 100.0,
		brand: "Rectangular",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [5, 1, 10],
		rating: 4.5,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["rectangular", "prescription"],
	},
	{
		id: 2,
		name: "Double Round Sunglasses",
		slug: "double-round-sunglasses",
		price: 325,
		previousPrice: 300,
		brand: "Round",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [6, 1, 7],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["round", "sunglasses"],
	},
	{
		id: 3,
		name: "Aviator Sunglasses",
		slug: "aviator-sunglasses",
		price: 160,
		brand: "Aviator",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [8, 1, 7],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 4,
		name: "Cat Eye Sunglasses",
		slug: "cat-eye-sunglasses",
		price: 96,
		previousPrice: 90,
		brand: "Cat Eye",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [1, 7, 9],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 5,
		name: "Gradient Aviator Sunglasses",
		slug: "gradient-aviator-sunglasses",
		price: 212,
		previousPrice: 200,
		brand: "Gradient",
		perex: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed auctor, purus sit amet volutpat.",
		categories: [8, 7, 1],
		rating: 4.5,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 6,
		name: "Square Prescription Eyeglass Frames",
		slug: "square-prescription-eyeglass-frames",
		price: 100,
		previousPrice: 120,
		brand: "Square",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [13, 1, 10],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 7,
		name: "Round Flat Lens Sunglasses",
		slug: "round-flat-lens-sunglasses",
		price: 368,
		previousPrice: 375,
		brand: "Round",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [6, 1, 7],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 8,
		name: "Clubmaster Square Prescription",
		slug: "clubmaster-square-prescription",
		price: 212,
		brand: "Round",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [10, 1],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 9,
		name: "Round Prescription Eyewear Frames",
		slug: "round-prescription-eyewear-frames",
		price: 48,
		brand: "Round",
		perex: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed auctor, purus sit amet volutpat.",
		categories: [6, 1, 10],
		rating: 4.5,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 10,
		name: "Clubround Round Sunglasses",
		slug: "clubround-round-sunglasses",
		price: 100,
		previousPrice: 120,
		brand: "Clubround",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [6, 1, 7],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 11,
		name: "Round Prescription Eyeglass Frames",
		slug: "round-prescription-eyeglass-frames",
		price: 410,
		brand: "Round",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [6, 1, 10],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 12,
		name: "Clubmaster Square Sunglasses",
		slug: "clubmaster-square-sunglasses",
		price: 430,
		brand: "Clubmaster",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [7, 1, 13],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},

	{
		id: 1,
		name: "Rectangular Prescription",
		slug: "rectangular-prescription",
		price: 52.0,
		previousPrice: 100.0,
		brand: "Rectangular",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [5, 1, 10],
		rating: 4.5,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["rectangular", "prescription"],
	},
	{
		id: 2,
		name: "Double Round Sunglasses",
		slug: "double-round-sunglasses",
		price: 325,
		previousPrice: 300,
		brand: "Round",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [6, 1, 7],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["round", "sunglasses"],
	},
	{
		id: 3,
		name: "Aviator Sunglasses",
		slug: "aviator-sunglasses",
		price: 160,
		brand: "Aviator",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [8, 1, 7],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 4,
		name: "Cat Eye Sunglasses",
		slug: "cat-eye-sunglasses",
		price: 96,
		previousPrice: 90,
		brand: "Cat Eye",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [1, 7, 9],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 5,
		name: "Gradient Aviator Sunglasses",
		slug: "gradient-aviator-sunglasses",
		price: 212,
		previousPrice: 200,
		brand: "Gradient",
		perex: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed auctor, purus sit amet volutpat.",
		categories: [8, 7, 1],
		rating: 4.5,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 6,
		name: "Square Prescription Eyeglass Frames",
		slug: "square-prescription-eyeglass-frames",
		price: 100,
		previousPrice: 120,
		brand: "Square",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [13, 1, 10],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 7,
		name: "Round Flat Lens Sunglasses",
		slug: "round-flat-lens-sunglasses",
		price: 368,
		previousPrice: 375,
		brand: "Round",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [6, 1, 7],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 8,
		name: "Clubmaster Square Prescription",
		slug: "clubmaster-square-prescription",
		price: 212,
		brand: "Round",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [10, 1],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 9,
		name: "Round Prescription Eyewear Frames",
		slug: "round-prescription-eyewear-frames",
		price: 48,
		brand: "Round",
		perex: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed auctor, purus sit amet volutpat.",
		categories: [6, 1, 10],
		rating: 4.5,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 10,
		name: "Clubround Round Sunglasses",
		slug: "clubround-round-sunglasses",
		price: 100,
		previousPrice: 120,
		brand: "Clubround",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [6, 1, 7],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 11,
		name: "Round Prescription Eyeglass Frames",
		slug: "round-prescription-eyeglass-frames",
		price: 410,
		brand: "Round",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [6, 1, 10],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 12,
		name: "Clubmaster Square Sunglasses",
		slug: "clubmaster-square-sunglasses",
		price: 430,
		brand: "Clubmaster",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [7, 1, 13],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},

	{
		id: 1,
		name: "Rectangular Prescription",
		slug: "rectangular-prescription",
		price: 52.0,
		previousPrice: 100.0,
		brand: "Rectangular",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [5, 1, 10],
		rating: 4.5,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["rectangular", "prescription"],
	},
	{
		id: 2,
		name: "Double Round Sunglasses",
		slug: "double-round-sunglasses",
		price: 325,
		previousPrice: 300,
		brand: "Round",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [6, 1, 7],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["round", "sunglasses"],
	},
	{
		id: 3,
		name: "Aviator Sunglasses",
		slug: "aviator-sunglasses",
		price: 160,
		brand: "Aviator",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [8, 1, 7],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 4,
		name: "Cat Eye Sunglasses",
		slug: "cat-eye-sunglasses",
		price: 96,
		previousPrice: 90,
		brand: "Cat Eye",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [1, 7, 9],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 5,
		name: "Gradient Aviator Sunglasses",
		slug: "gradient-aviator-sunglasses",
		price: 212,
		previousPrice: 200,
		brand: "Gradient",
		perex: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed auctor, purus sit amet volutpat.",
		categories: [8, 7, 1],
		rating: 4.5,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 6,
		name: "Square Prescription Eyeglass Frames",
		slug: "square-prescription-eyeglass-frames",
		price: 100,
		previousPrice: 120,
		brand: "Square",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [13, 1, 10],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 7,
		name: "Round Flat Lens Sunglasses",
		slug: "round-flat-lens-sunglasses",
		price: 368,
		previousPrice: 375,
		brand: "Round",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [6, 1, 7],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 8,
		name: "Clubmaster Square Prescription",
		slug: "clubmaster-square-prescription",
		price: 212,
		brand: "Round",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [10, 1],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 9,
		name: "Round Prescription Eyewear Frames",
		slug: "round-prescription-eyewear-frames",
		price: 48,
		brand: "Round",
		perex: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed auctor, purus sit amet volutpat.",
		categories: [6, 1, 10],
		rating: 4.5,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 10,
		name: "Clubround Round Sunglasses",
		slug: "clubround-round-sunglasses",
		price: 100,
		previousPrice: 120,
		brand: "Clubround",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [6, 1, 7],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 11,
		name: "Round Prescription Eyeglass Frames",
		slug: "round-prescription-eyeglass-frames",
		price: 410,
		brand: "Round",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [6, 1, 10],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 12,
		name: "Clubmaster Square Sunglasses",
		slug: "clubmaster-square-sunglasses",
		price: 430,
		brand: "Clubmaster",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [7, 1, 13],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},

	{
		id: 1,
		name: "Rectangular Prescription",
		slug: "rectangular-prescription",
		price: 52.0,
		previousPrice: 100.0,
		brand: "Rectangular",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [5, 1, 10],
		rating: 4.5,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["rectangular", "prescription"],
	},
	{
		id: 2,
		name: "Double Round Sunglasses",
		slug: "double-round-sunglasses",
		price: 325,
		previousPrice: 300,
		brand: "Round",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [6, 1, 7],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["round", "sunglasses"],
	},
	{
		id: 3,
		name: "Aviator Sunglasses",
		slug: "aviator-sunglasses",
		price: 160,
		brand: "Aviator",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [8, 1, 7],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 4,
		name: "Cat Eye Sunglasses",
		slug: "cat-eye-sunglasses",
		price: 96,
		previousPrice: 90,
		brand: "Cat Eye",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [1, 7, 9],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 5,
		name: "Gradient Aviator Sunglasses",
		slug: "gradient-aviator-sunglasses",
		price: 212,
		previousPrice: 200,
		brand: "Gradient",
		perex: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed auctor, purus sit amet volutpat.",
		categories: [8, 7, 1],
		rating: 4.5,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 6,
		name: "Square Prescription Eyeglass Frames",
		slug: "square-prescription-eyeglass-frames",
		price: 100,
		previousPrice: 120,
		brand: "Square",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [13, 1, 10],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 7,
		name: "Round Flat Lens Sunglasses",
		slug: "round-flat-lens-sunglasses",
		price: 368,
		previousPrice: 375,
		brand: "Round",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [6, 1, 7],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 8,
		name: "Clubmaster Square Prescription",
		slug: "clubmaster-square-prescription",
		price: 212,
		brand: "Round",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [10, 1],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 9,
		name: "Round Prescription Eyewear Frames",
		slug: "round-prescription-eyewear-frames",
		price: 48,
		brand: "Round",
		perex: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed auctor, purus sit amet volutpat.",
		categories: [6, 1, 10],
		rating: 4.5,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 10,
		name: "Clubround Round Sunglasses",
		slug: "clubround-round-sunglasses",
		price: 100,
		previousPrice: 120,
		brand: "Clubround",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [6, 1, 7],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 11,
		name: "Round Prescription Eyeglass Frames",
		slug: "round-prescription-eyeglass-frames",
		price: 410,
		brand: "Round",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [6, 1, 10],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 12,
		name: "Clubmaster Square Sunglasses",
		slug: "clubmaster-square-sunglasses",
		price: 430,
		brand: "Clubmaster",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [7, 1, 13],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},

	{
		id: 1,
		name: "Rectangular Prescription",
		slug: "rectangular-prescription",
		price: 52.0,
		previousPrice: 100.0,
		brand: "Rectangular",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [5, 1, 10],
		rating: 4.5,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["rectangular", "prescription"],
	},
	{
		id: 2,
		name: "Double Round Sunglasses",
		slug: "double-round-sunglasses",
		price: 325,
		previousPrice: 300,
		brand: "Round",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [6, 1, 7],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["round", "sunglasses"],
	},
	{
		id: 3,
		name: "Aviator Sunglasses",
		slug: "aviator-sunglasses",
		price: 160,
		brand: "Aviator",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [8, 1, 7],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 4,
		name: "Cat Eye Sunglasses",
		slug: "cat-eye-sunglasses",
		price: 96,
		previousPrice: 90,
		brand: "Cat Eye",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [1, 7, 9],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 5,
		name: "Gradient Aviator Sunglasses",
		slug: "gradient-aviator-sunglasses",
		price: 212,
		previousPrice: 200,
		brand: "Gradient",
		perex: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed auctor, purus sit amet volutpat.",
		categories: [8, 7, 1],
		rating: 4.5,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 6,
		name: "Square Prescription Eyeglass Frames",
		slug: "square-prescription-eyeglass-frames",
		price: 100,
		previousPrice: 120,
		brand: "Square",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [13, 1, 10],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 7,
		name: "Round Flat Lens Sunglasses",
		slug: "round-flat-lens-sunglasses",
		price: 368,
		previousPrice: 375,
		brand: "Round",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [6, 1, 7],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 8,
		name: "Clubmaster Square Prescription",
		slug: "clubmaster-square-prescription",
		price: 212,
		brand: "Round",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [10, 1],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 9,
		name: "Round Prescription Eyewear Frames",
		slug: "round-prescription-eyewear-frames",
		price: 48,
		brand: "Round",
		perex: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed auctor, purus sit amet volutpat.",
		categories: [6, 1, 10],
		rating: 4.5,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 10,
		name: "Clubround Round Sunglasses",
		slug: "clubround-round-sunglasses",
		price: 100,
		previousPrice: 120,
		brand: "Clubround",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [6, 1, 7],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 11,
		name: "Round Prescription Eyeglass Frames",
		slug: "round-prescription-eyeglass-frames",
		price: 410,
		brand: "Round",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [6, 1, 10],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
	{
		id: 12,
		name: "Clubmaster Square Sunglasses",
		slug: "clubmaster-square-sunglasses",
		price: 430,
		brand: "Clubmaster",
		perex: "Black Transparent UV Protection Classic sunglasses combine usefulness with the design. The perfect design will complement your face and top off any outfit. In combination with high-quality lenses, an excellent protection from harmful UV-rays is guaranteed. If you're searching forspecial protection, then polarized sunglasses are the right option for you....",
		categories: [7, 1, 13],
		rating: 4.9,
		countInStock: 5,
		// variants: ["gold", "white"],
		reviews: ["Great product", "Nice shoes"],
		tags: ["nike", "air max", "270"],
	},
];

export default dummyProducts;
